package cli

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newImportCmd(open func(ctx context.Context) (*deps, error)) *cobra.Command {
	var sourceName string
	cmd := &cobra.Command{
		Use:   "import <file.csv>",
		Short: "Import a bank/card CSV into the ledger",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			d, err := open(cmd.Context())
			if err != nil {
				return err
			}
			data, err := os.ReadFile(args[0])
			if err != nil {
				return err
			}
			res, err := d.importer.Import(cmd.Context(), data, sourceName)
			if err != nil {
				return err
			}
			out := cmd.OutOrStdout()
			cacheNote := "new mapping generated by AI"
			if res.MappingCached {
				cacheNote = "cached mapping reused"
			}
			fmt.Fprintf(out, "saved %d, duplicates skipped %d (%s)\n", res.Saved, res.DupSkipped, cacheNote)
			for _, f := range res.Failed {
				fmt.Fprintf(out, "  ! line %d not imported: %s (%s)\n", f.Line, f.Reason, f.Raw)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&sourceName, "source", "", "registered source name (required)")
	_ = cmd.MarkFlagRequired("source")
	return cmd
}
